### PR TITLE
Fixes #10

### LINKED ISSUE #10: Regridded cubes have BITPIX = -64 even when input cubes have BITPIX = -32
This doubles the file size and the memory requirement of mosaicking. I suggest we correct this.

Maybe we cannot force Montage to stick the the input data type, but we could consider converting the regridded FITS to the input FITS type after the fact.

### PR DESCRIPTION
**Pull request by sphemakh**
The output of the mosaic precision will now match that the input FITS file with the lowest precision. However, the montage image products are still 64-bit because of how the header template is created. @svw26 please have a look at how you make header templates and fix.

### CODE REVIEW

**Comment by svw26** [comment]
Hiya @SpheMakh , some montage_wrapper documentation made me think I could find a way to get montage to output 32-bit regridded files, but I tried different things to no avail. (Even with an edited header template, the BITPIX value is ignored.) Going back to the #10 thread, I tried @gigjozsa's suggestion but get different attribute errors. Please could you take a look at the relevant lines? (See my last commit.) x

**Comment by sphemakh** [comment]
@svw26 @paoloserra please have a careful look at my changes.

**Comment by paoloserra** [comment]
@SpheMakh it seems to me that `make_mosaic.py` is undoing lots of recent changes. Is it possible that something went wrong when merging `master` into `issue10`?

**Comment by paoloserra** [comment]
Some of the big changes I see and I don't understand are the disappearance of the function `estimate_noise` or the fact that `finite_array` is never updated / used.

**Comment by sphemakh** [comment]
It looks like the branch was already merged. So there is nothing to merge in this branch. Can you or @svw26 check if anything here is not in master already?

**Comment by paoloserra** [comment]
will do

**Comment by paoloserra** [comment]
It's a little difficult to understand what changes are still useful, but anyway this is what I think is going on and what I think we should do. Let me know whether that makes sense.

In `main.py`:
- The only change seems related to `check_for_files()`, which takes additional arguments in this PR. Those changes are not in current master. I'm not sure what those changes do though, I think it's just different coding style, but the end result is the same?

In `make_mosaic.py`:
- We add the `BITPIX` change in the montage `.hdr` file. I think this is what this PR was meant to fix so probably we want to keep this change.
- We delete `final_check_for_files()`. That's probably OK since the function is not used.
- We delete `gauss()` and `estimate_noise()`. I'm not sure why we're doing this. Those functions are needed. The lines using those functions are deleted, too, but that's not good because we need to measure the noise to fix #5 (fixed through #15). I think these changes need to be undone.
- We add `find_lowest_precision()`, which is needed for the `BITPIX` stuff above. So I think this change should be kept.
- Changes to how the mosaic array `mos_array` is filled (and other steps related to that) should probably be undone. It seems that this PR reverts changes made in #15, which are all tested and necessary.

**Comment by paoloserra** [comment]
@SpheMakh should I have a look again?

**Comment by sphemakh** [comment]
Yes, please

**Comment by paoloserra** [comment]
@SpheMakh this branch does not run. The function `check_for_files()` takes 2 arguments but is called with 4 arguments in `main.py`.

```
Traceback (most recent call last):
  File "/home/pserra/Astro/caracal-venv-3.7/bin/mosaic-queen", line 8, in <module>
    main.main(sys.argv[1:])
  File "/home/pserra/Astro/caracal-venv-3.7/lib/python3.7/site-packages/mosaicQueen/main.py", line 111, in main
    check_for_files(input_dir, images, 'images', args.regrid)  # This raises an error and exits if files are not found
TypeError: check_for_files() takes 2 positional arguments but 4 were given
```

Also, I noticed that we still define and use `final_check_for_files` in `make_mosaic.py`, which maybe you were trying to get rid of to use only `check_for_files()`. But I'm not 100% sure that was your intention.

**Comment by paoloserra** [comment]
I don't know how you were planning to use the extra 2 arguments (especially the last one) so I leave this to you.

**Comment by sphemakh** [comment]
Birth pangs of a large commit from an out-of-sync branch. Let me have a look. But we need to add a test suite to this repo to avoid these issues in the future.

**Comment by sphemakh** [comment]
I found the version of the function that takes 4 arguments and added it. Please test again

**Comment by paoloserra** [comment]
@SpheMakh The final mosaic FITS are now 32-bit as the input cubes, but the regridded FITS produced by montage are still 64-bit. Is that the intended behaviour?

**Comment by sphemakh** [comment]
Nope, that doesn't sound right. Is it possible to specify the precision of the output montagepy images?

**Comment by paoloserra** [comment]
I'm checking exactly that

**Comment by paoloserra** [comment]
So https://github.com/caracal-pipeline/MosaicQueen/blob/ab2954a50c8be97fbfc3fffc7802a802744a8c76/mosaicQueen/make_mosaic.py#L93 createds a header, which montage then uses for regridding. That header reads:

```
SIMPLE  = T
BITPIX  = -64
NAXIS   = 3
NAXIS1  = 492
NAXIS2  = 488
NAXIS3  = 20
CTYPE1  = 'RA---TAN'
CTYPE2  = 'DEC--TAN'
EQUINOX = 2000
CRVAL1  =  141.927169088
CRVAL2  =  -52.266490375
CRVAL3  = 1391626953.125000000
CRPIX1  =       246.5000
CRPIX2  =       244.5000
CRPIX3  =    1.000000000
CDELT1  =   -0.005555556
CDELT2  =    0.005555556
CDELT3  = 208984.375000000
CROTA2  =    0.462413789
END
```

So I'm going to try edit the header before regridding... right?

**Comment by paoloserra** [comment]
So I tried to edit the `.hdr` file from -64 to -32, but the regridding task `mProjectCube` crashes.

So I think we need to give up on that one.

I don't see anything related to this on the web.

Agreed?

**Comment by paoloserra** [comment]
Note that this was already pointed out by @gigjozsa , https://github.com/caracal-pipeline/MosaicQueen/issues/10#issuecomment-779784096

**Comment by paoloserra** [comment]
@SpheMakh I think I've found a way to at least convert the regridded images (which montage always produces as 64-bit) to the bitpix of the input images. Can you have a look whether this makes sense? Thanks.

**Comment by sphemakh** [comment]
Hi @paoloserra. Let's convert the FITS to the correct precision after montage does the regridding.

**Comment by paoloserra** [comment]
> Hi @paoloserra. Let's convert the FITS to the correct precision after montage does the regridding.

Yeah, well, that's exactly what I've impleemented here. :)  Can you have a look whether that's OK?

**Comment by sphemakh** [comment]
Looks good. I can't approve the PR because I created it, if you are happy with it lets merge.

**Review by paoloserra — APPROVED** [review]

**Pull request merged**
