### PR TITLE
add github action for ci test

### PR DESCRIPTION
**Pull request by sphemakh**

### CODE REVIEW

**Comment by paoloserra** [comment]
@SpheMakh I don't think we ever tried this with python > 3.8 . It's failing, but that's probably ok? Should we limit the test to <= 3.8 ?

**Comment by sphemakh** [comment]
I don't have admin privalages to turn off the travis-ci for this repo, @paoloserra can you please add me.

**Comment by paoloserra** [comment]
Try now?

**Comment by sphemakh** [comment]
All good now. Thanks.

**Comment by sphemakh** [comment]
Pushed it through because all the relevant tests passed.

**Pull request merged**
