### PR TITLE
distribute the reproj & #32 #34 #31

### LINKED ISSUE #7: Distribute the regridding over multiple CPUs
MosaicSteward works on a single CPU. In the case of large line cubes this is not ideal.

As an example, I have 24 line cubes, each with 1440x1440 5-arcsec pixels (2x2 deg^2 in total) and 2250 1.4-km/s channels (~3000 km/s in total). They're not crazy large -- each is 18GB is size.

Mosaicking them takes 2 days (1 h  to regrid each  `image.fits`, 1 h for each `pb.fits`). This is of the same order of the time it took me to make all those cubes in the first place.

In principle, each `image.fits` and each `pb.fits` could be regridded on a separate CPU, so it should be possible to gain significant speed here.

### LINKED ISSUE #31: MosaicQueen, mosaicQueen or mosaic-queen?
Following the recent name change, the repository is now called `MosaicQueen`, the folder with the code is called `mosaicQueen`, and the package name is `mosaic-queen`. Wouldn't it be better to stick to one name?

### LINKED ISSUE #32: Do we really need the option --mosaic-type ?
This can be `spectral` or `continuum` and is useful to decide which Montage function to use. But shouldn't MosaicQueen set this automatically depending on whether the input FITS are 3D or 2D? Why should the user be asked for this? @svw26 @SpheMakh maybe there was a reason which I'm forgetting?

### LINKED ISSUE #34: NAXIS>2 causes troubles
I am having troubles if I use MosaicQueen to do a mosaic starting from:

1.  Q and U Stokes images having NAXIS=4. This happens using either the spectrum or the continuum mode.
```
$ mosaic-queen -i /56TB_2/fornax/MFS-pol-imaging/images -t wsclean3.1-mgain99-thr2-bw1-mfs06-0000-Q-image.fits wsclean3.1-mgain99-thr2-bw1-mfs07-0000-Q-image.fits -o mos_output/mosaic -n 2points_00 -m continuum -r
2022-05-23 13:42:00,689 - MAKE_MOSAIC - INFO - Target images:
2022-05-23 13:42:00,690 - MAKE_MOSAIC - INFO -     wsclean3.1-mgain99-thr2-bw1-mfs06-0000-Q-image.fits
2022-05-23 13:42:00,690 - MAKE_MOSAIC - INFO -     wsclean3.1-mgain99-thr2-bw1-mfs07-0000-Q-image.fits
2022-05-23 13:42:00,690 - MAKE_MOSAIC - INFO - Will generate a mosaic from the input images.
2022-05-23 13:42:00,690 - MAKE_MOSAIC - INFO - If you would also like mosaics to be made from the associated models and residuals, please re-run with the '-a' argument enabled.
2022-05-23 13:42:00,690 - MAKE_MOSAIC - INFO - Checking for images and beams
2022-05-23 13:42:00,690 - MAKE_MOSAIC - INFO - All images found on disk
2022-05-23 13:42:00,690 - MAKE_MOSAIC - INFO - All beams found on disk
2022-05-23 13:42:00,694 - MAKE_MOSAIC - INFO - Checking for regridded images and beams
2022-05-23 13:42:00,694 - MAKE_MOSAIC - WARNING - File mos_output/mosaic/wsclean3.1-mgain99-thr2-bw1-mfs06-0000-Q-imageR.fits does not exist
2022-05-23 13:42:00,694 - MAKE_MOSAIC - WARNING - File mos_output/mosaic/wsclean3.1-mgain99-thr2-bw1-mfs07-0000-Q-imageR.fits does not exist
2022-05-23 13:42:00,694 - MAKE_MOSAIC - INFO - Regridded images are not all in place, so using montage to create them
2022-05-23 13:42:00,694 - MAKE_MOSAIC - INFO - Running montage tasks to create mosaic header ...
2022-05-23 13:42:00,694 - MAKE_MOSAIC - INFO -     mImgtbl -t mos_output/mosaic/2points_00_image_fields /56TB_2/fornax/MFS-pol-imaging/images mos_output/mosaic/2points_00_image_fields.tbl
2022-05-23 13:42:00,946 - MAKE_MOSAIC - INFO -     mMakeHdr mos_output/mosaic/2points_00_image_fields.tbl mos_output/mosaic/2points_00_image.hdr
2022-05-23 13:42:00,968 - MAKE_MOSAIC - INFO - Running montage tasks to regrid files ...
2022-05-23 13:42:00,968 - MAKE_MOSAIC - INFO -     mProject /56TB_2/fornax/MFS-pol-imaging/images/wsclean3.1-mgain99-thr2-bw1-mfs06-0000-Q-image.fits mos_output/mosaic/wsclean3.1-mgain99-thr2-bw1-mfs06-0000-Q-imageR.fits mos_output/mosaic/2points_00_image.hdr
2022-05-23 13:47:14,658 - MAKE_MOSAIC - INFO -     Convert from 64-bit to 32-bit ...
Traceback (most recent call last):
  File "/home/floi/caracal/bin/mosaic-queen", line 8, in <module>
    main.main(sys.argv[1:])
  File "/home/floi/caracal/lib/python3.6/site-packages/mosaicQueen/main.py", line 213, in main
    input_dir, output_dir, mosaic_type, 'image', images, imagesR, beams, beamsR, outname, bitpix, subimage_dict)
  File "/home/floi/caracal/lib/python3.6/site-packages/mosaicQueen/make_mosaic.py", line 235, in use_montage_for_regridding
    fits.writeto('{0:s}/{1:s}'.format(output_dir, cc.replace(image_type+'.fits', image_type+'R.fits')), Rfits[0].data.astype(dtype), header=head, overwrite=True)
  File "/home/floi/caracal/lib/python3.6/site-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/home/floi/caracal/lib/python3.6/site-packages/astropy/io/fits/convenience.py", line 420, in writeto
    checksum=checksum)
  File "/home/floi/caracal/lib/python3.6/site-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/home/floi/caracal/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 372, in writeto
    checksum=checksum)
  File "/home/floi/caracal/lib/python3.6/site-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/home/floi/caracal/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 920, in writeto
    self.verify(option=output_verify)
  File "/home/floi/caracal/lib/python3.6/site-packages/astropy/io/fits/verify.py", line 119, in verify
    raise VerifyError('\n' + '\n'.join(messages))
astropy.io.fits.verify.VerifyError: 
Verification reported errors:
HDU 0:
    NAXISj keyword out of range ('NAXIS3' when NAXIS == 2)
    NAXISj keyword out of range ('NAXIS4' when NAXIS == 2)
Note: astropy.io.fits uses zero-based indexing.
```
2. Q and U Stokes cubes. In this case the error is due to the fact that with NAXIS=4 the regridded images are empty. Therefore the noise is 'nan' and MosaicQueen crashes. Removing the fourth axis from the header and setting NAXIS=3 fixes the issue and the mosaic cubes are correctly made.

Can you add a function to prevent these errors?

### PR DESCRIPTION
**Pull request by paoloserra**
close #7

with thanks to @landmanbester

### CODE REVIEW

**Comment by paoloserra** [comment]
BTW I've checked that the output FITS files are identical to those in the non-parallel version of the code. Something to double-check again when reviewing.

**Comment by paoloserra** [comment]
new commit closes #34

**Comment by paoloserra** [comment]
new commit closes #32

**Comment by paoloserra** [comment]
Lots of changes to correct the missing length-1 axes (e.g., Stokes) and header keys in the output of Montage compared to the input images/cubes. Hopefully now the final output mosaics of MosaicQueen are consistent with the input images/cubes.

**Comment by francescaLoi** [comment]
I tested it, you have my blessing!

**Review by francescaLoi — APPROVED** [review]
I tested it with 4D images and cubes with PB images and cubes of different dimensions. It works well and it uses multiple cores if required.

**Pull request merged**
