### PR TITLE
Estimate noise

### LINKED ISSUE #5: Weighting of component images
[Raised by @paoloserra -- thanks!] For the overlapping region(s) in the mosaic, the package simply uses a mean average of the data. Instead, the typical noise of the component images should be taken into account, so that the data is weighted accordingly. x

### LINKED ISSUE #12: CROTA2 in the header should be a float, not a string
Issue raised for CARACal: https://github.com/caracal-pipeline/caracal/issues/1273

Fix via https://github.com/svw26/MosaicSteward/blob/e7cdb4f5dbb30af7cceeabb641691b5a086b40cc/MosaicSteward/make_mosaic.py#L56 x

### LINKED ISSUE #18: restfreq/restfrq not in mosaic header
I found that fits header keywords associated with the rest frequency and spectroscopic rest frame that were present in the original images and beam files are not transferred to the mosaic file.  I noticed because CARTA was giving me a very strange values for channel velocities in a mosaic.  It might be nice if these are maintained.

### LINKED ISSUE #19: Masked pixels become zero in mosaic, not NaN.
I'm mosaicking a pointing with a bunch of beams where the same channel is masked in all of them.  In the original cubes, these are masked, but in the mosaic all values are set to 0.  I think these should be NaNs so as not to be confused with pixels having real zero values (for example in source finding).
Screen Shot 2022-03-22 at 10 27 42

### PR DESCRIPTION
**Pull request by svw26**
To fix issue #5 , but please could someone check the weighting applied? I thought I'd 'blink' (in ds9) between the old and new 'image' mosaics (from before and after my work on this branch) and noticed that the new pixel-values appear to be a factor ~3 lower than before... which sounds dodgy, given that there are 3 images being combined in my test. (So a factor N missing somewhere?) Maybe I've not fully understood what the update_mos() function is doing... x

### CODE REVIEW

**Comment by svw26** [comment]
Also fixes #12

**Comment by svw26** [comment]
A reminder to please check this, ideally by comparing a mosaic from a much older run (with master) to what you get using this branch. x

**Comment by paoloserra** [comment]
I can confirm that there is a problem with the scaling. Below are two mosaics made from the same input cubes.

OLD (i.e., current CARACal)
Screenshot 2021-06-01 at 17 37 02

NEW (i.e., stand-alone MosaicSteward on branch `estimate_noise`)
Screenshot 2021-06-01 at 17 37 12

The greyscale is the same in the two images (nevermind that the NEW mosaic has no units), but the NEW mosaic has pixel values a factor ~4 lower. Also in this case, as reported above, this factor is similar to the nr of input cubes.

The noise level of the input cubes is ~ 2.5 mJy/beam. The noise level of the OLD mosaic cube is  ~ 2.2 mJy/beam, which makes sense given that the pointings overlap only marginally. The noise level of the NEW mosaic cube is ~0.6 mJy/beam, which is a factor ~ 4 lower than expected.

So I confirm that there is an issue with the normalization.

The noise cubes will also need some attention. At the moment they are in units of the single cube's noise (with the old assumption that  all cubes have the same input noise). However, we will want to change that to output noise cubes in Jy/beam.

**Comment by paoloserra** [comment]
Looking at the code I've noticed that we now mirror the distribution of pixel values around zero. Strictly, that  is not necessary. Calculating the MAD or RMS (or fitting a half-Gaussian) to negative pixels only -- without mirroring their distribution to create an equal nr of positive values -- will give you the correct estimate of the noise level.

The trick is that the MAD is calculated *assuming* that the distribution is centred on zero (even though it isn't, because all values are negative).  The same is true of the RMS. See code below.

```
>>> import numpy as np
>>> for ii in range(10):
...   vals = np.random.normal(loc=0,scale=1,size=10000)
...   valspos = vals[vals<=0]
...   print('shape_all = {0:}, shape_pos = {1:}, std_all = {2:.2f}, mad_all = {3:.2f}, mad_pos = {4:.2f}, rms_all = {5:.2f}, rms_pos = {6:.2f}'.format(vals.shape, valspos.shape, np.std(vals), np.median(np.abs(vals))*1.4826, np.median(np.abs(valspos))*1.4826, np.sqrt((vals**2).mean()), np.sqrt((valspos**2).mean())))
... 
shape_all = (10000,), shape_pos = (4992,), std_all = 1.01, mad_all = 1.02, mad_pos = 1.01, rms_all = 1.01, rms_pos = 1.00
shape_all = (10000,), shape_pos = (5057,), std_all = 1.01, mad_all = 1.00, mad_pos = 1.01, rms_all = 1.01, rms_pos = 1.00
shape_all = (10000,), shape_pos = (4958,), std_all = 0.99, mad_all = 1.00, mad_pos = 1.00, rms_all = 0.99, rms_pos = 0.99
shape_all = (10000,), shape_pos = (5018,), std_all = 1.00, mad_all = 1.00, mad_pos = 1.00, rms_all = 1.00, rms_pos = 1.00
shape_all = (10000,), shape_pos = (4973,), std_all = 0.99, mad_all = 1.00, mad_pos = 0.99, rms_all = 0.99, rms_pos = 0.99
shape_all = (10000,), shape_pos = (5046,), std_all = 1.00, mad_all = 1.00, mad_pos = 1.01, rms_all = 1.00, rms_pos = 1.00
shape_all = (10000,), shape_pos = (4951,), std_all = 1.00, mad_all = 1.00, mad_pos = 1.00, rms_all = 1.00, rms_pos = 1.00
shape_all = (10000,), shape_pos = (4943,), std_all = 1.00, mad_all = 0.99, mad_pos = 0.99, rms_all = 1.00, rms_pos = 1.00
shape_all = (10000,), shape_pos = (4981,), std_all = 1.01, mad_all = 1.03, mad_pos = 1.04, rms_all = 1.01, rms_pos = 1.02
shape_all = (10000,), shape_pos = (5077,), std_all = 1.00, mad_all = 1.02, mad_pos = 1.03, rms_all = 1.00, rms_pos = 1.00
```

**Comment by paoloserra** [comment]
So I was checking the code and it seems to me that the noise level of the individual input  cubes is missing from https://github.com/svw26/MosaicSteward/blob/126722e751f4d8eaf38bfd45ca77b7a3bb6c76e6/MosaicSteward/make_mosaic.py#L201

Just to make sure  we're on the same page I attach  my understanding of how mosaicking works.

Screenshot 2021-06-02 at 10 18 53

With reference to these equations, I think that the current code misses `1/sigma_i**2` from the normalisation cube `B`.

**Review by paoloserra — DISMISSED** [review]

**Review by paoloserra — DISMISSED** [review]

**Review by paoloserra — DISMISSED** [review]

**Comment by paoloserra** [comment]
Now that proper noise scaling is implemented we need to apply the same scaling when mosaicking model and residual cubes (enabled by the `-a` option). I'll do it in this PR.

**Review by paoloserra — APPROVED** [review]

**Pull request merged**
